### ISSUE TITLE
Create tutorial/more verbose help for users throughout Refinery

### ISSUE THREAD

**Issue by scottx611x** [parklab/refinery-platform#1212]
### TO-DO:
- [x] Create Generic component to provide "Help" on demand
- [x] Evaluate tutorial/overlay JS libraries
- [x] Create a basic tutorial for one of the processes mentioned below
    * **Upload data**
    * Visualize data
    * Browse Data
    * Setup & run an Analysis
    * Collaborate

---

### For a tutorial/overlay library check these out:

- Joyride | http://zurb.com/playground/jquery-joyride-feature-tour-plugin
- Intro.js | http://usablica.github.io/intro.js/
- Hopscotch | http://linkedin.github.io/hopscotch/
- Crumble | http://blog.tommoor.com/crumble/
- Pageguide | http://tracelytics.github.io/pageguide/
- Bootstro.js | http://clu3.github.io/bootstro.js/
- Chardin.js | https://github.com/heelhook/chardin.js

**Comment by scottx611x** [comment]
https://chatra.io/

**Comment by scottx611x** [comment]
This branch currently address the issue, but more as a proof of concept: https://github.com/parklab/refinery-platform/tree/scottx611x/tutorial_overlay

Related to #1226

**Comment by scottx611x** [comment]
**Example:**
![file_upload_tutorial](https://cloud.githubusercontent.com/assets/5629547/16659998/98d4ce3a-443a-11e6-8ac9-a5cdce96b3f0.gif)
