### ISSUE TITLE
Tutorial overlays for end users

### ISSUE THREAD

**Issue by scottx611x** [parklab/refinery-platform#1226]
Related to #1212 

Now that Refinery is going to have some end users, its a good idea to provide some tutorials, [other than a video](https://twitter.com/MarkKriegsman/status/739664279083814912) 😆 , so that our users have a better overall understanding of What they are able to do, and how to do it.

**TO-DO:**
- [x] Add "?" icon in top right to provide info about tutorials/general help
   - [x] Pulse or Highlight the above `if user.userprofile.login_count == 1` (migration was necessary here) to alert user that it exists and is helpful (could also potentially run tutorials automatically if this logic is reached)
   - [x] provide some type of popover containing info/links upon a click
- [x] take care of tutorials for all static content (Launch Pad, Collaborate, Upload data)
- [x] be able to start tutorials from the links in the popover
- [x] provide some way to go back and view tutorials again?
- [x] dont show `Help` if no one is logged in
- [x] `Find out how to update user model w/ Angular` track the viewing of each tutorial separately (tied to User......??? `User.tutorials_viewed`) then checkbox next to each item in popover
- [x] figure out why navigation between pages isn't working(see collab & upload tuts)
- [x] update user model not only on exit event, but if they view all "slides" and then click out of the overlay
- [x] Handle the initiation of tutorials from separate pages in Refinery (some elements arent available everywhere...)
- [x] Fix white tooltip background on white text (see collab tutorial)
- [x] Figure out why tutorials cant be re-run after being exited midway through
- [x] Deploy to AWS and get feedback
- [x] Test, test, test, test, test
- [x] pull out strings into configurable file
- [x] Be able to start tutorials from anywhere
- [ ] New tutorial based upon first upload of a Dataset??
   - [ ] take care of tutorials for content not immediately available within Refinery ( Visualize data, Browse Data, Setup & run an Analysis, Share a Dataset, tutorial for Tabular file options, once a file has been chosen)
