### ISSUE TITLE
Explore IGV.js and pileup.js integration options

### ISSUE THREAD

**Issue by scottx611x** [parklab/refinery-platform#1237]
We are migrating away from our current implementation of IGV in favor of a version embedded within Refinery due to the current imp. being not so user-friendly.

**Some potential options are:**
- **IGV** | http://igv.org/doc/doc.html
- **Pileup** | http://www.hammerlab.org/2015/06/19/introducing-pileup-js-a-browser-based-genome-viewer/

---
### TO-DO:

- [x] Weigh pros and cons of both options
- [x] Provide some proof of concept that this can be achieved with one (or both) of the above
- [x] Work on a more thorough integration

**Comment by mccalluc** [comment]
Glancing at both:
- IGV has some active development; Pileup has been very quiet in 2016.
- Both produce similar html: nested divs, with canvas elements for the tracks.
- Data sources:
  - Pileup: "This  can  be achieved  by  running  a  GA4GH  server.  pileup.js  supports  v0.5  of  the 
GA4GH  protocol  (Terry  et  al.,  2014).  Support  for  other  data  loading schemes can be added via user-defined sources."
  - IGV: I'm not confident whether it uses the same format as IGV java for high level indexes, but expect so. I can see it making byte range requests at the lowest level.
- IGV: 11 examples; Pileup: 2.
- Documentation: IGV has five detailed pages in the wiki. Pileup: "See /examples/playground.js for a complete set of track types.", and that file isn't very useful. 

IGV.js looks much more mature. Close?
