### ISSUE TITLE
Analysis Monitoring Front End Issues

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#553]
- [ ] Improve analysis progress monitoring UI #450 - 
If analysis input files are already available locally in the file store, the analysis preprocessing file "upload" progress bar turns green in seconds. On the other hand, actual upload into Galaxy is running for several minutes while execution progress bar shows no progress (since history is empty until a couple of files are uploaded into a library). Analysis stages should be labeled better and progress indicators should be more dynamic.

- [x] *[4]* change how analysis status is displayed in launch pad #242
This should be based on the new progress indicator UI elements to be developed for the "global" progress indicator.
Tasks:
    - [x] test analysis status before creating dynamic checks
    - [x] show progress for all three 3 phases: distinguish with different icons next to percent sign: upload, cog wheels, download Pivotal Tracker story 40822761 (Nils Gehlenborg - Dec 6, 2012)

- [x] *[20]* improve progress indicators #296
    - [x] *4h* no longer show "progress" page after analysis is launched and show confirmation dialog that analysis had started
    - [x] *16h* create a "menu" like compact progress indicator that is globally accessible
Pivotal Tracker story 46993653 (Nils Gehlenborg - Mar 27, 2013)

- [x] Analysis status view briefly shows "Analysis execution is pending" after analysis results have been downloaded. #397
Refinery log:
```
2014-03-03 15:42:18 DEBUG views analysis_status: analysis_manager.views.analysis_status called
2014-03-03 15:42:19 WARNING models execution_status: Unable to get progress for history '0b900c60f93c0654' of analysis 'Test workflow: SPP analog 2014-03-03 15:40:16.520406'
2014-03-03 15:42:21 DEBUG views analysis_status: analysis_manager.views.analysis_status called
2014-03-03 15:42:22 WARNING models execution_status: Unable to get progress for history '0b900c60f93c0654' of analysis 'Test workflow: SPP analog 2014-03-03 15:40:16.520406'
```
Cause: AnalysisMonitor keeps polling Galaxy history even after cleanup has finished (history was deleted).

- [x] Activity Monitor reports about 50% CPU utilization by Chrome browser during analysis monitoring (Intel i7 2.5GHz) #498
