### ISSUE TITLE
Dataset Browser moved to the AngularJS

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#831]
- Recreate views, controller, directives, etc
   - [ ] Dataset table
   - [ ] How we select/deselect nodes
   - [ ] Table attributes
- [ ] Create resources/services for api requests
- [ ] Handling login/permissions on the front end to avoid unnecessary API Calls 
- [ ] Minimize Trigger Global Events 
- [ ] #301 *[4]* stop requiring page reloads in sample selection interface 
- [ ] Easy unit tests (minimum)
- [ ] Integration tests
- [ ] Refactor existing angular code  (prevented previously due to framework splits) 
- [ ] #446 Avoid duplicating fields if they’re annotated as both a characteristic & factor 
- [ ] #713 Improve data model of data sets
- [ ] #639 The dataset nav feature needs refactoring
- [ ] Clean up old javascript/jquery code which is no longer in use

**Comment by jkmarx** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Hs21FuIF&#x2F;191-dataset-browser-enhancements"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Dataset Browser Enhancements</a>

**Comment by jkmarx** [comment]
Umbrella issues are now tracked in Trello.
